# Generated by Django 4.2.29 on 2026-09-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_analysis_language_report_dedup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='url',
            field=models.URLField(max_length=1000, unique=True),
        ),
    ]
